name: Documentation
description: Suggest improvements or report errors in the documentation
labels: ["documentation"]
body:
  - type: textarea
    id: doc-issue
    attributes:
      label: What part of the documentation is affected?
      description: Provide a link or description of the section.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: What is your suggestion?
      description: How can we make it clearer or more accurate?
    validations:
      required: true
